name: portfolyo
description: "Flutter ve Supabase ile mühendislik portföyü (projeler, CV, admin panel)."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^14.0.0

  # State Management
  provider: ^6.1.0

  # Fonts
  google_fonts: ^6.2.0

  # Icons
  cupertino_icons: ^1.0.8

  # Remote Database
  supabase_flutter: ^2.12.0

  # URL Launcher
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

dependency_overrides:

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/

