ALTER TABLE personal_info ADD COLUMN IF NOT EXISTS story TEXT;
ALTER TABLE personal_info ADD COLUMN IF NOT EXISTS vision TEXT;
ALTER TABLE personal_info ADD COLUMN IF NOT EXISTS approach TEXT;
ALTER TABLE personal_info ADD COLUMN IF NOT EXISTS why_me TEXT;